- hosts: localhost
  connection: local
  gather_facts: false
  user: root
  pre_tasks:
    - include_vars: variables.yml	  
	
# Advanced example with tagging and CloudWatch

tasks:
     -name: ec2 with tagging and cloudwatch
	  ec2:
    key_name: "{{ ec2_keypair }}"
    group: "{{ ec2_security_group_id }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}" 
	vpc_subnet_id: "{{ ec2_subnet_id }}"
    assign_public_ip: yes
	region: "{{ ec2_region }}"
    wait: true
	exact_count: "{{ ec2_count }}"
    Role: "{{ ec2_tag_Role }}"
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: "{{ ec2_volume_size }}"
            delete_on_termination: true
      register: ec2
    monitoring: yes
	
	
