- name: Packer
  hosts: 'all'
  become: yes
  become_method: sudo
  tasks:
    - name: install the latest version of the packages
      package:
        name:
          - httpd
          - httpd-tools
          - mod_ssl
          - php
          - php-devel
          - php-mysql
          - php-pdo
          - php-mbstring
          - php-gd
          - php-xml
          - php-xmlrpc
          # - php-mcrypt
          - php-pear
          - git
        state: latest

    - name: enable services
      systemd:
        name: httpd
        state: started
        enabled: yes
        
    - name: clone git repo
      git: repo=https://github.com/CasperNaudts/Cloud-web-files.git dest=/var/www/html update=no