- name: Packer
  hosts: 'all'
  become: yes
  become_method: sudo
  tasks:
    - name: install the latest version of the packages
      package:
        name:
          - httpd
          - httpd-tools
          - mod_ssl
          - php
          - php-devel
          - php-mysql
          - php-pdo
          - php-mbstring
          - php-gd
          - php-xml
          - php-xmlrpc
          # - php-mcrypt
          - php-pear
          - git
        state: latest
    
    - name: Command for Datadog
      shell: DD_API_KEY=a6987f86ca776c7912448d8a0d06731f bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/datadog-agent/master/cmd/agent/install_script.sh)"       

    - name: enable services
      systemd:
        name: httpd
        state: started
        enabled: yes
        
    - name: clone git repo
      git: repo=https://github.com/CasperNaudts/Cloud-web-files.git dest=/var/www/html update=no
    
    
