- hosts: localhost
  connection: local
  gather_facts: false
  user: root
 	  
	

- hosts: apache
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
  
  
- name: install packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - apache2
        - git
	
- name: clone html template
  git: repo=https://github.com/CasperNaudts/webapp/blob/master/testfile.html dest=/var/www/testfile.html update=no


- Name: install html


- Name: install php





	
	
